# nu_plugin_secret Configuration Example
# 
# This file shows all available configuration options for the nu_plugin_secret plugin.
# Copy this file to ~/.config/nushell/plugins/secret/config.toml and modify as needed.

# Configuration file version (for migration purposes)
version = "1.0"

[redaction]
# Global redaction style: "typed_brackets", "simple", "asterisks", "brackets", or custom text
style = "typed_brackets"

# Custom redaction text (only used when style = custom)
# custom_text = "[SECRET]"

# Whether to show type information in redaction text
show_type_info = true

# Whether to preserve length information in redaction (security consideration)
preserve_length = false

# Per-type redaction style overrides
[redaction.per_type]
# string = "asterisks"
# binary = "simple"
# int = "brackets"

# Per-context redaction style overrides
[redaction.per_context]
# display = "typed_brackets"
# debug = "simple"
# serialization = "simple"
# audit = "simple"


[security]
# Security level: "minimal", "standard", "paranoid"
level = "standard"

# Audit configuration changes to system logs
audit_config_changes = true

# Maximum length for custom redaction text
max_custom_text_length = 50


# Example configurations for different use cases:

# High Security Environment (minimal information disclosure):
# [redaction]
# style = "simple"
# show_type_info = false
# preserve_length = false
# [security]
# level = "paranoid"

# Development Environment (more informative):
# [redaction]
# style = "typed_brackets" 
# show_type_info = true
# preserve_length = true
# [security]
# level = "minimal"

# Custom Branded Environment:
# [redaction]
# style = "custom"
# custom_text = "[COMPANY_SECRET]"
# show_type_info = false
# [security]
# level = "standard"