# Configuration for cargo-deny
# See https://embarkstudios.github.io/cargo-deny/checks/cfg.html

[graph]
targets = []
all-features = true

[advisories]
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# A list of advisory IDs to ignore
ignore = [
    # Transitive dependency from nushell - paste crate unmaintained but still functional
    "RUSTSEC-2024-0436",
]

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    # Additional licenses required by nushell dependencies
    "0BSD",           # BSD Zero Clause License (doctest-file, recvmsg)
    "Zlib",           # zlib License (foldhash)
    "MPL-2.0",        # Mozilla Public License 2.0 (option-ext)
    "CC-PDDC",        # Creative Commons Public Domain Dedication (pwd)
    "Unicode-3.0",    # Unicode License v3 (unicode-ident)
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "allow"
# Lint level for when a crate's version requirement uses ranges
allow-wildcard-paths = false

[sources]
# Lint level for what to happen when a crate from a crate registry that is not
# in the allow list is encountered
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered  
unknown-git = "warn"
# List of allowed registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of allowed Git repositories
allow-git = []