name: Feature Request
description: Suggest a new feature or enhancement for nu_plugin_secret
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the form below with as much detail as possible.
        
        This plugin prioritizes security above all else. Please consider how your feature request maintains or enhances security.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you want...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the specific use case or problem this feature would solve
      placeholder: |
        I need this feature because...
        This would help when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: |
        The feature could work by...
        A new command could be added that...
    validations:
      required: true

  - type: textarea
    id: security-considerations
    attributes:
      label: Security Considerations
      description: How does this feature maintain the security-first principles of the plugin?
      placeholder: |
        This feature maintains security by...
        The sensitive data would be protected by...
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New secret type
        - New command
        - Performance improvement
        - Developer experience
        - Documentation
        - Security enhancement
        - Integration with other tools
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my use of the plugin
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches or workarounds have you considered?
      placeholder: |
        I considered...
        Currently I work around this by...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: If applicable, provide examples of how this feature would be used
      placeholder: |
        # Example usage:
        let secret_data = "sensitive" | secret wrap
        $secret_data | secret new-command
      render: nushell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: This feature aligns with the security-first principles of the plugin
          required: true
        - label: I have provided all the requested information above
          required: true